set(CPACK_PACKAGE_NAME                "protopong")
set(CPACK_PACKAGE_VERSION_MAJOR       ${PONG_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR       ${PONG_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH       ${PONG_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION             ${PONG_VERSION})
set(CPACK_PACKAGE_INSTALL_DIRECTORY   "ProtoPong")
set(CPACK_PACKAGE_VENDOR              "gonrogon <gonrogon@gmail.com>")
set(CPACK_PACKAGE_CONTACT             "gonrogon")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A cross-plataform pong designed for educational purposes.")
set(CPACK_PACKAGE_DESCRIPTION_FILE    "${CMAKE_SOURCE_DIR}/README.md")
set(CPACK_RESOURCE_FILE_LICENSE       "${CMAKE_SOURCE_DIR}/COPYING.txt")
set(CPACK_PACKAGE_EXECUTABLES         "protopong;ProtoPong")
set(CPACK_CREATE_DESKTOP_LINKS        "ProtoPong")
set(CPACK_INSTALL_CMAKE_PROJECTS      "${main_BINARY_DIR}/protopong-prefix/src/protopong-build;protopong;ALL;/")
set(CPACK_PROJECT_CONFIG_FILE         "${main_BINARY_DIR}/CPackOptions.cmake")

configure_file("${CMAKE_CURRENT_LIST_DIR}/CPackOptions.cmake.in" "${main_BINARY_DIR}/CPackOptions.cmake" @ONLY)

include(CPack)
